doctrine_migrations:
    migrations_paths:
        'App\Company\Infrastructure\Doctrine\Migrations':
            '%kernel.project_dir%/src/Company/Infrastructure/Doctrine/Migrations'
    enable_profiler: false