doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            CompanyEntity:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/config/doctrine/Company/Entity'
                prefix: App\Company\Domain\Entity
            ContractEntity:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/config/doctrine/Contract/Entity'
                prefix: App\Contract\Domain\Entity
            ContractValueObject:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/config/doctrine/Contract/ValueObject'
                prefix: App\Contract\Domain\ValueObject
            EmployeeEntity:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/config/doctrine/Employee/Entity'
                prefix: App\Employee\Domain\Entity
            PayrollEntity:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/config/doctrine/Payroll/Entity'
                prefix: App\Payroll\Domain\Entity
            PayrollValueObject:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/config/doctrine/Payroll/ValueObject'
                prefix: App\Payroll\Domain\ValueObject
            PolicyEntity:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/config/doctrine/Policy/Entity'
                prefix: App\Policy\Domain\Entity

when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system